name: Run Hello.py on Merge to Main

# on:
#   push:
#     branches:
#       - main  # Trigger only when a PR is merged into main

on:
  pull_request:
    branches:
      - main  # Trigger only when a PR is merged into the 'main' branch
    types:
      - closed  # We want to trigger the workflow when the PR is closed (merged)

jobs:
  run-python-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Install boto3
      run: |
        pip install boto3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2  # Change to your region

    - name: Print AWS environment variables
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"

    - name: Validate merged branch
      run: |
        echo "Base branch is: ${{ github.base_ref }}"
        if [[ "${{ github.base_ref }}" == "main" ]]; then
          echo "Read desired branch"
          echo "Printing this message for confirmation"
        else
          echo "The branch on which change is made is not the main branch."
          exit 1
        fi
        
    # - name: Test AWS Credentials
    #   run: aws sts get-caller-identity

    - name: Run hello.py
      run: |
        echo "Running hello.py"
        python hello.py

    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v4
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: us-east-2  # Change to your region

    # - name: Upload config.yaml to S3
    #   run: |
    #     echo "Uploading config.yaml to S3..."
    #     aws s3 cp config.yaml s3://sugnyani-patil/Config    
    - name: Configure Git user
      run: |
        git config --global user.name "sugnyani-patil"
        git config --global user.email "patilsugnyani@gmail.com"

    - name: Commit and Push changes
      run: |
        git add .
        git diff --cached --quiet || git commit -m "Auto-commit changes from hello.py"
        git push    
